services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email javierpf000@gmail.com --agree-tos --no-eff-email -d javierpardofernandez.com
    networks:
      - app-network

networks:
  app-network:
    external: true 